config/routes.rb
Rails.application.routes.draw do
  
  # get 'home/index'
  
  resources :relationships
  resources :posts
  devise_for :users, controllers: {registrations: 'devise/registrations'}
  resources :users, :except => [:index]
  

  get 'home/timeline'

  # routes for user profile 
  # get 'users/:id' => 'users#index', as: :profile
  # patch 'users/:id' => 'users#edit'
  # put 'users/:id' => 'users#edit'

  root to: "posts#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader 

  has_many :posts
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name: 'Relationship',
                                   dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  accepts_nested_attributes_for :posts
  
  def feed
    Post.from_users_followed_by(self)
  end
  
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    @user.avatar = params[:file]
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  #@user.save!
  #@user.avatar.url # => '/url/to/file.png'
  #@user.avatar.current_path # => 'path/to/file.png'
  #@user.avatar_identifier # => 'file.png'

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
    @relationship = Relationship.where(
      follower_id: current_user.id,
      followed_id: @user.id
    ).first_or_initialize if current_user
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  def profile
    @user = User.find(params[:id])
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

private

  def user_params
    params.require(:user).permit(:name, :username, :email, :avatar, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@user.errors.count, "error") %> prevented this change from saving:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label My Avatar %><br>
  <%= f.file_field :avatar %><br>
  
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>

  # more profiley stuff here

<!-- original size
<%= image_tag(@user.avatar)%>

large size
<%= image_tag(@user.avatar.large_avatar)%>

medium size
<%= image_tag(@user.avatar.medium_avatar)%>

small size
<%= image_tag(@user.avatar.small_avatar)%> -->
  
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
edit.html.erb
#user can edit or destroy profile

app/views/users/show.html.erb
<h1><%=@user.username  %>'s Profile Page</h1>
<p><%= image_tag(@user.avatar.url) %></p>

<h3> Posts: (<%=@user.posts.count%>)</h3>

<% @posts.each do |post|  %>
  <div class="link row clearfix">
    <h2>
      <%=  post.body %><br>
      <small class="author">Submitted <%= time_ago_in_words(post.created_at) %> ago</small>
    </h2>
  </div>
<% end %>

<% if current_user and @user != current_user %>
  <% if current_user.following? @user %>
    <%= form_tag relationship_path, method: :delete do %>
      <%= submit_tag "Unfollow" %>
    <% end %>
  <% else %>
    <%= form_for @relationship do %>
      <%= hidden_field_tag :followed_id, @user.id %>
      <%= submit_tag "Follow" %>
    <% end %>
  <% end %>
<% end %>

<%= paginate @posts %>