config/routes.rb
Rails.application.routes.draw do
  
  # get 'home/index'
  
  resources :relationships
  resources :posts
  devise_for :users, controllers: {registrations: 'devise/registrations'}
  resources :users, :except => [:index]
  

  get 'home/timeline'

  # routes for user profile 
  # get 'users/:id' => 'users#index', as: :profile
  # patch 'users/:id' => 'users#edit'
  # put 'users/:id' => 'users#edit'

  root to: "posts#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true, length: { maximum: 140 }

  accepts_nested_attributes_for :user

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
      user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #before_action :signed_in_user, only: [:create, :destroy]
  before_action :current_user, only: [:create, :destroy]

  # TODO: show all tweets despite non-signed in user.
  def index
    scope = user_signed_in? ? current_user.feed : Post

    @posts = scope.page(params[:page]).per(5).order('created_at DESC')

    respond_to do |format|
      format.html
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def timeline
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new

  end

  def create
    @post = Post.create(post_params)
    if @post.save
      flash[:success] = 'Chirp created!'
      redirect_to posts_url
    
    else
      flash[:danger] = @post.errors.full_messages.to_sentence
      redirect_to root_url
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = 'Chirp deleted!'
    redirect_to posts_url
  end

  private

    def post_params
      params.require(:post).permit(:body, :user_id, :username)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end



    ## yet another `correct_user` imprementation
    # def correct_user
    #   @micropost = current_user.posts.find(params[:id])
    # rescue
    #   redirect_to root_url
    # end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.hidden_field(:user_id, :value => current_user.id) %>
  </div>
  
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<div class="blog-post"> 
	<% @posts.each do |post| %>
	    <div>
	    	<img class="avatar" src="<%= post.user.avatar.small_avatar %>"> 
	    	<h3><%= post.body %></h3>
	      <h5>posted <%= link_to time_ago_in_words(post.created_at), post %> ago by <%= link_to post.user.username, user_path(post.user.id) %></h5>
	    </div>
	<% end %>
</div><!-- /.blog-post -->
 
<%= paginate @posts, :window => 2 %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div>
	<img class="avatar" src="<%= @post.user.avatar.small_avatar %>"> 
	<h3><%= @post.body %></h3>
	<h5>posted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.username %></h5>
	 
	<% if @post.user == current_user %>
	<h6><%= link_to post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } do %>
	Delete</h6>
  <% end %>
  <% end %>
</div>

app/views/posts/timeline.html.erb
<div>
  <img class="avatar" src="<%= @post.user.avatar.small_avatar %>"> 
  <h3><%= @post.body %></h3>
  <h5>posted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.username %></h5>
   
  <% if @post.user == current_user %>
  <h6><%= link_to post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } do %>
  Delete</h6>
  <% end %>
  <% end %>
</div>