config/routes.rb
Rails.application.routes.draw do
  
  # get 'home/index'
  
  resources :relationships
  resources :posts
  devise_for :users, controllers: {registrations: 'devise/registrations'}
  resources :users, :except => [:index]
  

  get 'home/timeline'

  # routes for user profile 
  # get 'users/:id' => 'users#index', as: :profile
  # patch 'users/:id' => 'users#edit'
  # put 'users/:id' => 'users#edit'

  root to: "posts#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <title>Chirp</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item"><%= link_to 'Home', posts_path %></a>
          <% if user_signed_in? -%>
            <a class="blog-nav-item"><%= link_to 'Profile', user_path(current_user) %></a>
            <a class="blog-nav-item"><%= link_to 'Edit Account', edit_user_registration_path %></a>
            <a class="blog-nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></a>
            <a class="blog-nav-item"><%= link_to 'New Post', new_post_path %></a>
          <% else %>
            <a class="blog-nav-item"><%= link_to 'Want to join?', new_user_registration_path %></a>
            <a class="blog-nav-item"><%= link_to 'Sign in', new_user_session_path %></a>
          <% end -%>
        </nav>
      </div>
    </div>

    <div id="main_content" class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <div class="container">

      <div class="blog-header">
        <%= image_tag "chirp_logo.png", class: "icon" %>
        <h1 class="blog-title">Chirp</h1>
        <p class="lead blog-description">The future of microblogging is here.</p>
      </div>

      <div class="row">

        <div class="col-sm-3 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Quick blurb about the user--maybe a short bio, follower/following count, and avatar?</p>
          </div>  
        </div><!-- /.blog-sidebar -->

        <div class="col-sm-8 blog-main">
          <%= yield %>
        </div><!-- /.blog-main -->

      </div><!-- /.row -->
    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://www.theironyard.com">The Iron Yard</a> by Aaron Harvey and Kelly Bristol</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>
  </body>
</html>


    
    